export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";
export const CREATE_COMMENT_RESET = "CREATE_COMMENT_RESET";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
