export const ALL_FEEDS_SUCCESS = "ALL_FEEDS_SUCCESS";
export const ALL_FEEDS_FAIL = "ALL_FEEDS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const CREATE_FEED_SUCCESS = "CREATE_FEED_SUCCESS";
export const CREATE_FEED_FAIL = "CREATE_FEED_FAIL";
export const CREATE_FEED_RESET = "CREATE_FEED_RESET";

