//basic info
export const ALL_BASIC_INFO_SUCCESS = "ALL_BASIC_INFO_SUCCESS";
export const ALL_BASIC_INFO_FAIL = "ALL_BASIC_INFO_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
//work info
export const ALL_WORK_INFO_SUCCESS = "ALL_WORK_INFO_SUCCESS";
export const ALL_WORK_INFO_FAIL = "ALL_WORK_INFO_FAIL";
//academic info
export const ALL_ACADEMIC_INFO_SUCCESS = "ALL_ACADEMIC_INFO_SUCCESS";
export const ALL_ACADEMIC_INFO_FAIL = "ALL_ACADEMIC_INFO_FAIL";
